volumes:
  postgres-data:
    external: true
services:
  frontend:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    # depends_on:
    #   - database
  #   environment:
  #     DATABASE_URL: postgres://wardrobe:password@database:5432/wardrobe
  #     WAIT_HOSTS: database:5432
  #     WAIT_TIMEOUT: 240
  # database:
  #   image: postgres:14.5-bullseye
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: snowstat_sadmin
  #     POSTGRES_USER: snowstats_admin
  #     POSTGRES_DB: snowstats_db
  #   ports:
  #     - 15432:5432
