# Generated by Django 4.0.3 on 2023-11-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Green', 'Green'), ('Blue', 'Blue'), ('Black', 'Black'), ('Double Black', 'Double Black'), ('Chairlift', 'Chairlift')], max_length=50)),
            ],
        ),
    ]
