# Generated by Django 4.0.3 on 2023-11-07 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stevenspass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='stevenspass.categoryvo'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src', models.CharField(max_length=150)),
                ('vote', models.IntegerField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='stevenspass.run')),
            ],
        ),
    ]
